# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeArcList <- function(nn) {
    .Call('_CIDnetworks_makeArcList', PACKAGE = 'CIDnetworks', nn)
}

makeEdgeList <- function(nn) {
    .Call('_CIDnetworks_makeEdgeList', PACKAGE = 'CIDnetworks', nn)
}

makeEdgeListSelfies <- function(nn) {
    .Call('_CIDnetworks_makeEdgeListSelfies', PACKAGE = 'CIDnetworks', nn)
}

symBlock <- function(entries) {
    .Call('_CIDnetworks_symBlock', PACKAGE = 'CIDnetworks', entries)
}

eldc <- function(latentSpacePos, edgelist) {
    .Call('_CIDnetworks_eldc', PACKAGE = 'CIDnetworks', latentSpacePos, edgelist)
}

cosineClosenessC <- function(latentSpacePos, edgelist) {
    .Call('_CIDnetworks_cosineClosenessC', PACKAGE = 'CIDnetworks', latentSpacePos, edgelist)
}

coincidence <- function(edgelist, nodes) {
    .Call('_CIDnetworks_coincidence', PACKAGE = 'CIDnetworks', edgelist, nodes)
}

xty <- function(edgelist, outcome, nodes) {
    .Call('_CIDnetworks_xty', PACKAGE = 'CIDnetworks', edgelist, outcome, nodes)
}

